<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope"
    xmlns:tt="http://www.onvif.org/ver10/schema"
    xmlns:tds="http://www.onvif.org/ver10/device/wsdl"
>
    <s:Body>
        <tds:GetSystemDateAndTimeResponse>
            <tds:SystemDateAndTime>
                <tt:UTCDateTime>
                    <tt:Date>
                        <tt:Year>__YEAR_UTC__</tt:Year>
                        <tt:Month>__MONTH_UTC__</tt:Month>
                        <tt:Day>__DAY_UTC__</tt:Day>
                    </tt:Date>
                    <tt:Time>
                        <tt:Hour>__HOUR_UTC__</tt:Hour>
                        <tt:Minute>__MINUTE_UTC__</tt:Minute>
                        <tt:Second>__SECOND_UTC__</tt:Second>
                    </tt:Time>
                </tt:UTCDateTime>
                <tt:LocalDateTime>
                    <tt:Date>
                        <tt:Year>__YEAR__</tt:Year>
                        <tt:Month>__MONTH__</tt:Month>
                        <tt:Day>__DAY__</tt:Day>
                    </tt:Date>
                    <tt:Time>
                        <tt:Hour>__HOUR__</tt:Hour>
                        <tt:Minute>__MINUTE__</tt:Minute>
                        <tt:Second>__SECOND__</tt:Second>
                    </tt:Time>
                </tt:LocalDateTime>
                <tt:TimeZone>
                    <tt:TZ>KoreaStandardTime-9</tt:TZ>
                </tt:TimeZone>
            </tds:SystemDateAndTime>
        </tds:GetSystemDateAndTimeResponse>
    </s:Body>
</s:Envelope>
